version: "3.9"
services:
  postgres:
    restart: always
    image: postgres:14.2
    environment:
      POSTGRES_DB: "charity"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./pgdata:/var/lib/posgresql/data
    ports:
      - "5434:5434"
